Atualizar projeto para novo padrão
betrybe/sd-0x-project-movie-card-library-crud-rubric pull request #1
Opened 2021-02-11 14:31 UTC by LucasSGomide

2021-02-23 14:34 UTC, brunobatista25 requested changes

2021-02-23 14:34 UTC, brunobatista25 commented on package.json
> +    "eslint": "^6.8.0",
aqui ta com o chapeu de versao

2021-02-23 14:34 UTC, brunobatista25 commented on package.json
> +    "eslint-config-trybe-frontend": "^1.1.0",
aqui tbm deixa como fixo a versao

2021-02-23 14:34 UTC, brunobatista25 commented on README.md
>  ```
aqui vc remove esses ```
 e poe espaco entre eles assim

- Será validado se a rota `/` renderiza a página MovieList

- Será validado se a rota `/movies/:id` renderiza a página MovieDetails

Fazer para todos os outros tbm

2021-02-25 14:12 UTC, brunobatista25 approved these changes

2021-03-02 11:26 UTC, LizzardMedeiros approved these changes
Show de bola! Ótimo trabalho!

2021-05-12 13:30 UTC, merged